---
# tasks file for mysql

- name: start mariadb
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Create a new database
  mysql_db:
    name: "{{ db_name }}"

- name: Configure new MySQL user
  mysql_user: 
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
